# Generated by Django 5.1.7 on 2025-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='movies/')),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
